### ISSUE TITLE
add imagine ai

### ISSUE THREAD

**Issue by GasmiAbdou** [FuseFairy/DiscordBot-GeminiAI#1]
add imagine ai o the bot :)

**Comment by FuseFairy** [comment]
The official api is not yet open for image generation.

**Comment by GasmiAbdou** [comment]
nah .. i mean integrate a random imagine ai api like kadnisky3 from https://fusionbrain.ai/en/ it's great and free to use from API  !

**Comment by FuseFairy** [comment]
But my repo are dedicated to Google AI, so that's kind of weird

**Comment by GasmiAbdou** [comment]
can you create an ai bot that uses kadnisky3 from https://fusionbrain.ai/en/  soon ?

**Comment by FuseFairy** [comment]
Maybe later.
