### ISSUE TITLE
Gemini Using Cookies 

### ISSUE THREAD

**Issue by Freenoob7878** [FuseFairy/DiscordBot-GeminiAI#2]
I think this is better than using the api. https://github.com/dsdanielpark/Gemini-API

**Comment by FuseFairy** [comment]
there is an expiration problem with cookies, but image generation I can use the cookie method first

**Comment by Freenoob7878** [comment]
Yeh the cookies expiration problem. I'm currently working on it but can't find any solution yet.

**Comment by FuseFairy** [comment]
There are other issues, such as the lack of stability. I'll keep an eye on it. Thank you.

**Comment by Freenoob7878** [comment]
I will close this issue now 
I just wanted to give suggestion.
